replicaCount: 1

image:
  name: dhiguerosr/kubernetes-demo
  pullPolicy: IfNotPresent
  tag: "1.0.0"

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 3000

resources: {}

nodeSelector: {}